version: 0.2
env:
  variables:
    
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the justiceleague-tracker
    - mvn install
artifacts:
  files:
  - target/testdemo.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'